//
// Created by Lo Yu Sum on 5/14/2023.
//

#ifndef MINECRAFT_VK_MINECRAFT_WORLD_CHUNK_CHUNKPOOLTYPE_HPP
#define MINECRAFT_VK_MINECRAFT_WORLD_CHUNK_CHUNKPOOLTYPE_HPP

class WorldChunk;
using ChunkTy = WorldChunk;

#endif   // MINECRAFT_VK_MINECRAFT_WORLD_CHUNK_CHUNKPOOLTYPE_HPP
